name: Upload components to the registry

on:
  push:
    branches:
      - main

jobs:
  upload_components:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Upload components
        uses: magicarm22/upload-components-ci-action@feature/compote_command
        env:
          DEFAULT_COMPONENT_SERVICE_URL: https://components-staging.espressif.com/api
        with:
          name: test
          directories: cmp
          namespace: dmitry
          api_token: ${{ secrets.IDF_COMPONENT_API_TOKEN }}
